name: library_management
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  dynamic_color: ^1.6.5
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.4.0
  input_quantity: ^1.1.6

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
