name: library_management
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  dynamic_color: ^1.6.5
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.4.0
  flutter_riverpod: ^2.3.6
  input_quantity: ^1.1.6
  uuid: ^3.0.7
  qr_flutter: ^4.1.0
  share_plus: ^7.1.0
  screenshot: ^2.1.0
  mobile_scanner: ^3.4.1
  native_qr: ^0.0.3
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
